apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: openwms-services
  namespace: default
spec:
  revisionTemplate:
    spec:
      container:
        image: docker.io/interface21/openwms-services:latest
        ports:
          - containerPort: 8761
