apiVersion: apps/v1
kind: Deployment
metadata:
  name: owms-services
  labels:
    app: owms-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owms-services
  template:
    metadata:
      labels:
        app: owms-services
    spec:
      containers:
        - name: service-registry
          image: interface21/openwms-services:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: owms-services
spec:
  ports:
  - port: 8761
  selector:
    app: owms-services