apiVersion: apps/v1
kind: Deployment
metadata:
  name: oleap-registry
  labels:
    app: oleap-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oleap-registry
  template:
    metadata:
      labels:
        app: oleap-registry
    spec:
      containers:
        - name: service-registry
          image: openleap/openleap-registry:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: oleap-registry
spec:
  ports:
  - port: 8761
  selector:
    app: oleap-registry