apiVersion: v1
kind: Service
metadata:
  name: oleap-registry
  labels:
    app: oleap-registry
spec:
  type: LoadBalancer
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: oleap-registry
