apiVersion: v1
kind: Service
metadata:
  name: owms-services
  labels:
    app: owms-services
spec:
  type: LoadBalancer
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: owms-services
