spring:
  application:
    name: openwms-services
  security:
    user:
      name: user
      password: sa

server:
  port: ${PORT:8761}

owms:
  eureka:
    url: ${owms.srv.protocol}://${spring.security.user.name}:${spring.security.user.password}@${owms.srv.hostname}:${server.port}
    zone: ${owms.eureka.url}/eureka/
  srv:
    protocol: http
    hostname: localhost

# https://medium.com/@fahimfarookme/the-mystery-of-eureka-self-preservation-c7aa0ed1b799
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false # default is true
    fetch-registry: false # default is true
    instance-info-replication-interval-seconds: 10 # default is 30
    service-url:
      defaultZone: ${owms.eureka.zone} # Must be camelCase
  server:
    wait-time-in-ms-when-sync-empty: 0 # default is 60000
    eviction-interval-timer-in-ms: 60000 # default is 60000
    enable-self-preservation: false # default is true
    renewal-percent-threshold: 0.49 # default is 0.85
    peer-node-read-timeout-ms: 1000 # default is 200
  instance:
    secure-port-enabled: false
    non-secure-port-enabled: true
    metadata-map:
      username: ${spring.security.user.name}
      password: ${spring.security.user.password}
      protocol: ${owms.srv.protocol}
      zone: ${owms.eureka.zone}
    # hostname: ${owms.srv.hostname} # to avoid 401 batch update errors

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "prometheus"
  server:
    port: ${MGMTPORT:8990}



