version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/app
permissions:
  - object: /home/ubuntu/app
    owner: ubuntu
    mode: 755
    type:
      - files
hooks:
  ApplicationStart:
    - location: runapp.sh
      timeout: 300
      runas: ubuntu
