apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: openleap-registry
  namespace: default
spec:
  revisionTemplate:
    spec:
      container:
        image: docker.io/openleap/openleap-registry:latest
        ports:
          - containerPort: 8761
